### PR TITLE
3.8.x tensorflow

### PR DESCRIPTION
**Pull request by Wulfsta**
Fix mistakes from #7

### CODE REVIEW

**Comment by Wulfsta** [comment]
@acowley I'm going to fix a few more things actually, I'll ping you when done.

**Comment by acowley** [comment]
Great! Can you swap `rocm-runtime` in place of `rocr`? The longer name is what is used in `nixpkgs` now.

**Comment by acowley** [comment]
Also we can think about if we can CI either the TF wheel or source build if they’re not too long.

**Comment by Wulfsta** [comment]
I expect the current state of things will work, but I haven't finished testing. `rocr` has been swapped. I don't know if you want to build this from source, it takes my machine an hour or so - not sure how long it will take CI.

**Comment by Wulfsta** [comment]
I take that back, now it's right.

**Comment by Wulfsta** [comment]
Oh oops, I meant to merge this into `3.8.x`.

**Comment by Wulfsta** [comment]
There, once the previous pull is reverted, this should be good to go.

**Comment by Wulfsta** [comment]
Have you had a chance to test yet? This derivation appears to work for me, but I have not extensively tested.

**Comment by Wulfsta** [comment]
So I was asking around on IRC about how to deal with the Python API for `gmsh`, and was shown [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/libevdev/default.nix). Take a look at how the file is patched - this might be a better way to do this than our current `sed` target, but requires more manual work to implement and maintain. We also might miss some symlinks and make Bazel mad, but I wanted to point it out to you to get your thoughts.

**Comment by acowley** [comment]
I like the way you've done it! There are pros and cons to sed-style patching, but they're mostly not very relevant in this instance. What you've done even lets us more easily add extra paths if so desired. The upside to patching each path separately would be to demonstrate that our build isn't *that* customized, is that right? I'm sympathetic to that, so if you have strong feelings either way then follow your heart.

**Comment by Wulfsta** [comment]
I'm more prone to the sort of hack I've done here, but I think what I've done is more obfuscated than what manual patching would look like. I would prefer to keep it how it is because it's the solution that requires the least amount of upkeep. I just wanted to see if it had any obvious benefits that we should consider.

**Comment by Wulfsta** [comment]
I'm tempted to bring PyTorch up to date but don't really have the motivation to remember/rediscover how that build works...

**Comment by acowley** [comment]
The `tensorflow2-rocm` build took somewhere over 3 hours for me. I ended up with a working TF2 that did not have GPU acceleration. When I set `rocmSupport = true;` in the definition of `tensorflow2-rocm` in `all-packages.nix`, I get the same Hunk failed error I saw with the previous PR (there, I had created my own `tensorflow2-rocm` definition where I also set `rocmSupport = true`).

**Comment by Wulfsta** [comment]
Oh boy that was a dumb mistake on my part. I'll fix that and test.

**Comment by Wulfsta** [comment]
I pushed a fixed patch, I'm testing now.

**Comment by Wulfsta** [comment]
Looks like we need to use at least [this](https://github.com/tensorflow/tensorflow/pull/42689) commit.

**Pull request merged**
