### PR TITLE
rocblas: update cmake flags

### PR DESCRIPTION
**Pull request by Wulfsta**
Opening a pull for this since `asm_full` is building. Hopefully this pushes us towards working high level libraries.

### CODE REVIEW

**Comment by Wulfsta** [comment]
You might want to review this and check to see if we need to feed anything else into Tensile - I think that we're good, but there might be some well-hidden issues there.

**Comment by acowley** [comment]
The CI build failure looks like we have the formatting of an architecture list wrong.

**Comment by Wulfsta** [comment]
Oh, that `;` should probably be a `,`? Let me try that.

**Comment by Wulfsta** [comment]
Oh wait it's much more annoying.

**Comment by Wulfsta** [comment]
That is less than elegant, but it should get the job done.

**Comment by acowley** [comment]
Oh jiminy, we really have to pick one or all?  That’s amazing. 🤦‍♂️

I had thought your original setup was right, so I guess I didn’t read the cmake closely enough. It seemed like it would take the value from the usual list of AMD targets given a certain path through the conditionals. May be worth opening an upstream issue if that’s right.

**Comment by Wulfsta** [comment]
Yeah this one is such a strange design choice that I didn't even think to test it. I might open an upstream issue, but haven't traced it closely enough to be sure that is the only way to do that.

**Comment by Wulfsta** [comment]
[I think this is the only way to go about this?](https://github.com/ROCmSoftwarePlatform/Tensile/blob/e93f8fd23f0f43bb298e7c5007dcc8d82baaed67/Tensile/Source/CMakeLists.txt#L117)

**Comment by Wulfsta** [comment]
Oh! `gfx803` is not in that list.

**Comment by Wulfsta** [comment]
There, `gfx803` is included in the flag `gfx000` which builds backup kernels that work for any architecture.

**Comment by Wulfsta** [comment]
I no longer understand why this is failing.

**Comment by acowley** [comment]
At least in the past, `gfx000` was not `all` but a default value returned by the enumerator in addition to actually detected hardware.

**Comment by Wulfsta** [comment]
This has got to be a bug, one of the errors I've gotten while trying other delimiters is
```
TensileCreateLibrary: error: argument --architecture: invalid choice: 'gfx000,gfx900,gfx906' (choose from 'all', 'gfx000', 'gfx803', 'gfx900', 'gfx906', 'gfx908')
```
but formatting as a semicolon delimited string fails and puts the next element as that of 'Tensile_LIBRARY_FORMAT' as you can see in the current failure. The strangest I've seen is with a string, that tells me 
```
CMake Error: The source directory "/build/source/build/gfx906" does not exist.
```
I'm officially baffled by this one.

**Comment by acowley** [comment]
Using `all` works, though? If so, let's go with that unless using a single architecture is selected by the NixOS user and that makes cmake happy. I thought CI had made more progress on your length-check version, but I may have misread on mobile.

**Comment by Wulfsta** [comment]
Yeah, I tested this one locally before pushing and it should be happy. I'm just baffled about this issue after reading the cmake and thought it was me making an absolutely silly mistake.

**Pull request merged**
