### PR TITLE
Add Tensorflow built from source

### PR DESCRIPTION
**Pull request by Wulfsta**
This is dependent on #6 and unstable getting to a point where [this commit](https://github.com/NixOS/nixpkgs/pull/95824) is in it for `tensorflow-estimator_2` to be updated. Unfortunately I have not set things up to test this packaging, but the important parts build. I'm looking for feedback on if you think this is a good way to go about this and potentially upstream this to `nixpkgs` once everything is building and working. This packaging does force a question - how should we handle the various `AMDGPU_TARGETS` flags? Our current method makes me wonder if we should be using an override and pass the targets (similar to what `rocrand` had) or continue using `config`?

### CODE REVIEW

**Comment by Wulfsta** [comment]
This now builds and appears to work with what's in `nixpkgs`! Can you confirm?

**Comment by acowley** [comment]
Should I be doing the from source tensorflow-rocm build? Do we want to try to get CI to build it?

**Comment by acowley** [comment]
Hm, the `rocm-create-sed-target.patch` is failing to apply at Hunk #1 for me. I may have done something wrong, but I don't know how to drop into a `nix-shell` to step through the main bazel build. I'm also a little surprised that `postFixup` only mentions `cudatoolkit`.

**Comment by Wulfsta** [comment]
I will look into all this later today. I will say that I don't understand why that patch is failing to apply, that's strange. I have been working from `configuration.nix`, but you should be able to create a `nix-shell` with `nix-shell -p 'python3.withPackages(ps: with ps; [ tensorflow2-rocm ])'`.

**Comment by acowley** [comment]
A problem is that `bazel-build` is bound in a `let`, so a shell that builds `tensorflow2-rocm`, for example, would need `bazel-build` already built. E.g. `nix-shell '<nixpkgs>' -A tensorflow2-rocm`.

Another possible problem is that I don't think you updated `all-packages.nix`, so I updated the old `tensorflow-rocm` attribute since its `bin.nix` was moved, and I added,

```nix
  tensorflow2-rocm = python37Packages.callPackage ./development/libraries/tensorflow/2 {
    inherit (self) miopen-hip miopengemm rocrand hipcub rocsparse hipsparse
                   rocfft rocblas rocm-runtime rccl;
    rocmSupport = true;
    hip = self.hip-clang;
  };
```

**Comment by Wulfsta** [comment]
Oh, I bet I did `git add .` out of a directory that wasn't the root. I'll fix this later.

**Pull request merged**
